from pathlib import Path
p=Path('/mnt/data/v2136_edit')
api=p/'src/main/java/com/sdebria/app/controller/ApiController.java'
s=api.read_text()
# aggregate saves
s=s.replace("SUM(red_cards) red_cards, SUM(fouls) fouls, SUM(goals_conceded) goals_conceded,\n                       SUM(clean_sheet) clean_sheets", "SUM(red_cards) red_cards, SUM(fouls) fouls, SUM(goals_conceded) goals_conceded,\n                       SUM(clean_sheet) clean_sheets, SUM(saves) saves")
s=s.replace("CASE WHEN p.position='ENTRENADOR' THEN 0 ELSE COALESCE(s.clean_sheets,0) END clean_sheets,", "CASE WHEN p.position='ENTRENADOR' THEN 0 ELSE COALESCE(s.clean_sheets,0) END clean_sheets,\n                   CASE WHEN p.position='ENTRENADOR' THEN 0 ELSE COALESCE(s.saves,0) END saves,")
# player profile sums
s=s.replace("CASE WHEN p.position='ENTRENADOR' THEN 0 ELSE COALESCE(SUM(s.clean_sheet),0) END clean_sheets,", "CASE WHEN p.position='ENTRENADOR' THEN 0 ELSE COALESCE(SUM(s.clean_sheet),0) END clean_sheets,\n                       CASE WHEN p.position='ENTRENADOR' THEN 0 ELSE COALESCE(SUM(s.saves),0) END saves,")
# Insert stats: add role and saves
old="""            int goalsConceded=keeper?Math.max(0,nz(s.goalsConceded())):0;\n            int cleanSheet=keeper&&goalsConceded==0?1:0;\n            jdbc.update(\"\"\"\n                INSERT INTO match_player_stats(match_id,player_id,minutes,goals,assists,big_mistakes,yellow_cards,red_cards,fouls,goals_conceded,clean_sheet,starter)\n                VALUES(?,?,?,?,?,?,?,?,?,?,?,?)\n                \"\"\",id,s.playerId(),nz(s.minutes()),eventGoals,eventAssists,nz(s.bigMistakes()),eventYellow,eventRed,eventFouls,goalsConceded,cleanSheet,s.starter()?1:0);"""
new="""            boolean goalkeeperStats=keeper && s.goalkeeperStats();\n            int goalsConceded=goalkeeperStats?Math.max(0,nz(s.goalsConceded())):0;\n            int cleanSheet=goalkeeperStats&&goalsConceded==0?1:0;\n            int saves=goalkeeperStats?Math.max(0,nz(s.saves())):0;\n            jdbc.update(\"\"\"\n                INSERT INTO match_player_stats(match_id,player_id,minutes,goals,assists,big_mistakes,yellow_cards,red_cards,fouls,goals_conceded,clean_sheet,saves,goalkeeper_stats,starter)\n                VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)\n                \"\"\",id,s.playerId(),nz(s.minutes()),eventGoals,eventAssists,nz(s.bigMistakes()),eventYellow,eventRed,eventFouls,goalsConceded,cleanSheet,saves,goalkeeperStats?1:0,s.starter()?1:0);"""
if old not in s: raise SystemExit('finish block not found')
s=s.replace(old,new)
# stats endpoint
s=s.replace("r.put(\"botellines\",awardLeaderboard(\"BOTELLIN\"));r.put(\"chapas\",awardLeaderboard(\"CHAPA\"));r.put(\"cleanSheets\",goalkeeperLeaderboard(\"SUM(s.clean_sheet)\"));r.put(\"goalsConceded\",goalkeeperLeaderboard(\"SUM(s.goals_conceded)\"));", "r.put(\"botellines\",awardLeaderboard(\"BOTELLIN\"));r.put(\"chapas\",awardLeaderboard(\"CHAPA\"));r.put(\"cleanSheets\",goalkeeperLeaderboard(\"SUM(s.clean_sheet)\"));r.put(\"goalsConceded\",goalkeeperLeaderboard(\"SUM(s.goals_conceded)\"));r.put(\"saves\",goalkeeperLeaderboard(\"SUM(s.saves)\"));")
s=s.replace("public record PlayerStatRequest(Long playerId,boolean played,boolean starter,Integer minutes,Integer goals,Integer assists,Integer bigMistakes,Integer yellowCards,Integer redCards,Integer fouls,Integer goalsConceded,boolean cleanSheet)", "public record PlayerStatRequest(Long playerId,boolean played,boolean starter,Integer minutes,Integer goals,Integer assists,Integer bigMistakes,Integer yellowCards,Integer redCards,Integer fouls,Integer goalsConceded,boolean cleanSheet,Integer saves,boolean goalkeeperStats)")
api.write_text(s)

mig=p/'src/main/java/com/sdebria/app/DatabaseMigration.java'
s=mig.read_text()
s=s.replace('addColumn("match_player_stats","clean_sheet","INTEGER NOT NULL DEFAULT 0");', 'addColumn("match_player_stats","clean_sheet","INTEGER NOT NULL DEFAULT 0");\n        addColumn("match_player_stats","saves","INTEGER NOT NULL DEFAULT 0");\n        addColumn("match_player_stats","goalkeeper_stats","INTEGER NOT NULL DEFAULT 1");')
mig.write_text(s)

schema=p/'src/main/resources/schema.sql'
s=schema.read_text()
s=s.replace('  clean_sheet INTEGER NOT NULL DEFAULT 0,\n  starter INTEGER NOT NULL DEFAULT 0,', '  clean_sheet INTEGER NOT NULL DEFAULT 0,\n  saves INTEGER NOT NULL DEFAULT 0,\n  goalkeeper_stats INTEGER NOT NULL DEFAULT 1,\n  starter INTEGER NOT NULL DEFAULT 0,')
schema.write_text(s)

js=p/'src/main/resources/static/js/app.js'
s=js.read_text()
# players list table and card keeper saves
s=s.replace("`${p.goals_conceded} GC · ${p.clean_sheets} 🧤`", "`${p.goals_conceded} GC · ${p.clean_sheets} 🧤 · ${p.saves} 🧤 Paradas`")
s=s.replace("<div class=\"hover-stat\"><b>${p.clean_sheets}</b><span>🧤</span></div>", "<div class=\"hover-stat\"><b>${p.clean_sheets}</b><span>🧤</span></div><div class=\"hover-stat\"><b>${p.saves}</b><span>Paradas</span></div>")
# profile stats goalkeeper
s=s.replace("...(keeper?[[\'Goles encajados\',p.goals_conceded],[\'Porterías a 0\',\'🧤 \'+p.clean_sheets]]:[])", "...(keeper?[[\'Goles encajados\',p.goals_conceded],[\'Porterías a 0\',\'🧤 \'+p.clean_sheets],[\'Paradas\',p.saves]]:[])")
# match player detail add saves and only keeper info perhaps
s=s.replace("<div class=\"mini-stat\"><small>Goles encajados</small><b>${stats.goals_conceded||0}</b></div>", "${positionLabel(p.position)==='PORTERO'&&stats.goalkeeper_stats!==0?`<div class=\"mini-stat\"><small>Goles encajados</small><b>${stats.goals_conceded||0}</b></div><div class=\"mini-stat\"><small>Paradas</small><b>${stats.saves||0}</b></div>`:''}")
# render stats saves block
s=s.replace("block('Goles encajados','🥅','goalsConceded'),block('Tarjetas'", "block('Goles encajados','🥅','goalsConceded'),block('Paradas','🧤','saves'),block('Tarjetas'")
# finish form header
s=s.replace("<span>Faltas*</span><span>GC</span><span>0*</span><span>Nota</span>", "<span>Faltas*</span><span>GC</span><span>0*</span><span>Paradas</span><span>Portero</span><span>Nota</span>")
# Replace row construction portion via targeted exact
old="""const st=existing[String(p.id)]||{},ev=eventStats(p.id),keeper=positionLabel(p.position)==='PORTERO',gc=keeper?Math.max(0,Number(st.goals_conceded||0)):0,cs=keeper&&!!st.id&&gc===0;return `<div class=\"finish-player\" data-id=\"${p.id}\"><span><b>#${p.shirt_number} ${esc(p.nickname)}</b><small>${esc(positionLabel(p.position))}</small></span><span>${starterIds.has(String(p.id))?'⭐ Titular':'Banquillo'}</span><input class=\"played\" type=\"checkbox\" ${st.id?'checked':''}><input class=\"minutes\" type=\"number\" min=\"0\" value=\"${st.minutes||0}\"><input class=\"goals derived-stat\" type=\"number\" min=\"0\" value=\"${ev.goals}\" readonly title=\"Se calcula automáticamente con los eventos\"><input class=\"assists derived-stat\" type=\"number\" min=\"0\" value=\"${ev.assists}\" readonly title=\"Se calcula automáticamente con los eventos\"><input class=\"bigMistakes\" type=\"number\" min=\"0\" value=\"${st.big_mistakes||0}\"><input class=\"yellowCards derived-stat\" type=\"number\" min=\"0\" value=\"${ev.yellow}\" readonly title=\"Se calcula automáticamente con los eventos\"><input class=\"redCards derived-stat\" type=\"number\" min=\"0\" value=\"${ev.red}\" readonly title=\"Se calcula automáticamente con los eventos\"><input class=\"fouls derived-stat\" type=\"number\" min=\"0\" value=\"${ev.fouls}\" readonly title=\"Se calcula automáticamente con los eventos\"><input class=\"goalsConceded\" type=\"number\" min=\"0\" value=\"${gc}\" ${keeper?'title=\"Introduce manualmente los goles encajados por este portero\"':'disabled title=\"Solo se aplica a porteros\"'}><input class=\"cleanSheet derived-stat\" type=\"checkbox\" ${cs?'checked':''} disabled title=\"Se calcula automáticamente con el resultado\"><input class=\"rating\" type=\"number\" min=\"0\" max=\"10\" step=\"0.01\" value=\"${existingRatings[String(p.id)]??''}\" placeholder=\"—\"></div>`"""
new="""const st=existing[String(p.id)]||{},ev=eventStats(p.id),keeper=positionLabel(p.position)==='PORTERO',goalkeeperStats=keeper?(st.id?Number(st.goalkeeper_stats??1)!==0:true):false,gc=keeper&&goalkeeperStats?Math.max(0,Number(st.goals_conceded||0)):0,cs=keeper&&goalkeeperStats&&!!st.id&&gc===0;return `<div class=\"finish-player\" data-id=\"${p.id}\"><span><b>#${p.shirt_number} ${esc(p.nickname)}</b><small>${esc(positionLabel(p.position))}</small></span><span>${starterIds.has(String(p.id))?'⭐ Titular':'Banquillo'}</span><input class=\"played\" type=\"checkbox\" ${st.id?'checked':''}><input class=\"minutes\" type=\"number\" min=\"0\" value=\"${st.minutes||0}\"><input class=\"goals derived-stat\" type=\"number\" min=\"0\" value=\"${ev.goals}\" readonly title=\"Se calcula automáticamente con los eventos\"><input class=\"assists derived-stat\" type=\"number\" min=\"0\" value=\"${ev.assists}\" readonly title=\"Se calcula automáticamente con los eventos\"><input class=\"bigMistakes\" type=\"number\" min=\"0\" value=\"${st.big_mistakes||0}\"><input class=\"yellowCards derived-stat\" type=\"number\" min=\"0\" value=\"${ev.yellow}\" readonly title=\"Se calcula automáticamente con los eventos\"><input class=\"redCards derived-stat\" type=\"number\" min=\"0\" value=\"${ev.red}\" readonly title=\"Se calcula automáticamente con los eventos\"><input class=\"fouls derived-stat\" type=\"number\" min=\"0\" value=\"${ev.fouls}\" readonly title=\"Se calcula automáticamente con los eventos\"><input class=\"goalsConceded\" type=\"number\" min=\"0\" value=\"${gc}\" ${keeper&&goalkeeperStats?'':'disabled'} title=\"Goles encajados manuales\"><input class=\"cleanSheet derived-stat\" type=\"checkbox\" ${cs?'checked':''} disabled title=\"Se calcula automáticamente\"><input class=\"saves\" type=\"number\" min=\"0\" value=\"${keeper&&goalkeeperStats?(st.saves||0):0}\" ${keeper&&goalkeeperStats?'':'disabled'} title=\"Paradas del portero\"><label class=\"keeper-role-toggle\" title=\"Si se desmarca, este portero se contabiliza como jugador de campo y no suma estadísticas de portería\"><input class=\"goalkeeperStats\" type=\"checkbox\" ${goalkeeperStats?'checked':''} ${keeper?'':'disabled'}> </label><input class=\"rating\" type=\"number\" min=\"0\" max=\"10\" step=\"0.01\" value=\"${existingRatings[String(p.id)]??''}\" placeholder=\"—\"></div>`"""
if old not in s: raise SystemExit('js row not found')
s=s.replace(old,new)
# stats payload add fields
s=s.replace("goalsConceded:$('.goalsConceded',r).disabled?0:Math.max(0,+$('.goalsConceded',r).value),cleanSheet:false", "goalsConceded:$('.goalsConceded',r).disabled?0:Math.max(0,+$('.goalsConceded',r).value),cleanSheet:false,saves:$('.saves',r).disabled?0:Math.max(0,+$('.saves',r).value),goalkeeperStats:$('.goalkeeperStats',r).checked")
# Add listener for toggle to enable/disable fields and awards refresh
needle="$$('.played').forEach(i=>i.onchange=refreshAwards);refreshAwards();"
rep="$$('.played').forEach(i=>i.onchange=refreshAwards);$$('.goalkeeperStats').forEach(i=>i.onchange=()=>{const r=i.closest('.finish-player');$('.goalsConceded',r).disabled=!i.checked;$('.saves',r).disabled=!i.checked;if(!i.checked){$('.goalsConceded',r).value=0;$('.saves',r).value=0;$('.cleanSheet',r).checked=false}});refreshAwards();"
if needle not in s: raise SystemExit('listener needle not found')
s=s.replace(needle,rep)
js.write_text(s)
